name: CommandBlocks
author: Ad5001
main: Ad5001\CMDBlock\main
version: 1.1.1
api: [2.0.0]
commands:
    cmdblock:
        description: Get help about cmd blocks
        usage: /cmdblock
        permission: cmdblock.cmd
permissions:
    cmdblock.create:
        default: op
    cmdblock.cmd:
        default: op
