name: CommandBlocks
author: Ad5001,TheDragonRing,HimbeersaftLP
main: Ad5001\CMDBlock\main
version: 1.0.0
api: [1.0.0]
commands:
    cmdblock:
        description: Change the command of a commandblock.
        usage: /cmdblock
        permission: cmdblock.cmd
permissions:
    cmdblock.create:
        default: op
    cmdblock.cmd:
        default: op
